In [3]:
import pandas as pd

In [9]:
df15 = pd.read_csv("/Users/almaroshani/Desktop/extra-exercises/merging/archive/2015.csv")
df16 = pd.read_csv("/Users/almaroshani/Desktop/extra-exercises/merging/archive/2016.csv")
df17 = pd.read_csv("/Users/almaroshani/Desktop/extra-exercises/merging/archive/2017.csv")
df18 = pd.read_csv("/Users/almaroshani/Desktop/extra-exercises/merging/archive/2018.csv")
df19 = pd.read_csv("/Users/almaroshani/Desktop/extra-exercises/merging/archive/2019.csv")
print(df15.columns)
print(df16.columns)
print(df17.columns)
print(df18.columns)
print(df19.columns)

Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Standard Error', 'Economy (GDP per Capita)', 'Family',
       'Health (Life Expectancy)', 'Freedom', 'Trust (Government Corruption)',
       'Generosity', 'Dystopia Residual'],
      dtype='str')
Index(['Country', 'Region', 'Happiness Rank', 'Happiness Score',
       'Lower Confidence Interval', 'Upper Confidence Interval',
       'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)',
       'Freedom', 'Trust (Government Corruption)', 'Generosity',
       'Dystopia Residual'],
      dtype='str')
Index(['Country', 'Happiness.Rank', 'Happiness.Score', 'Whisker.high',
       'Whisker.low', 'Economy..GDP.per.Capita.', 'Family',
       'Health..Life.Expectancy.', 'Freedom', 'Generosity',
       'Trust..Government.Corruption.', 'Dystopia.Residual'],
      dtype='str')
Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='str')
Index(['Overall rank', 'Country or region', 'Score', 'GDP per capita',
       'Social support', 'Healthy life expectancy',
       'Freedom to make life choices', 'Generosity',
       'Perceptions of corruption'],
      dtype='str')

In [11]:
df15["year"] = 2015
df16["year"] = 2016
pd.concat([df15, df16])

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,year,Lower Confidence Interval,Upper Confidence Interval
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,NaN,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,2016,3.404,3.564
153,Afghanistan,Southern Asia,154,3.360,NaN,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558,2016,3.288,3.432
154,Togo,Sub-Saharan Africa,155,3.303,NaN,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,2016,3.192,3.414
155,Syria,Middle East and Northern Africa,156,3.069,NaN,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,2016,2.936,3.202
156,Burundi,Sub-Saharan Africa,157,2.905,NaN,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,2016,2.732,3.078

In [12]:
#pasting two datasets one below the other:

pd.concat([df15,df16])

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,year,Lower Confidence Interval,Upper Confidence Interval
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
152,Benin,Sub-Saharan Africa,153,3.484,NaN,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,2016,3.404,3.564
153,Afghanistan,Southern Asia,154,3.360,NaN,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558,2016,3.288,3.432
154,Togo,Sub-Saharan Africa,155,3.303,NaN,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,2016,3.192,3.414
155,Syria,Middle East and Northern Africa,156,3.069,NaN,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,2016,2.936,3.202
156,Burundi,Sub-Saharan Africa,157,2.905,NaN,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,2016,2.732,3.078

In [13]:
#pasting two datasets one below the other WITHOUT repeated index:

pd.concat([df15,df16] , ignore_index=True)

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,year,Lower Confidence Interval,Upper Confidence Interval
0,Switzerland,Western Europe,1,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,0.29678,2.51738,2015,NaN,NaN
1,Iceland,Western Europe,2,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,0.43630,2.70201,2015,NaN,NaN
2,Denmark,Western Europe,3,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,0.34139,2.49204,2015,NaN,NaN
3,Norway,Western Europe,4,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,0.34699,2.46531,2015,NaN,NaN
4,Canada,North America,5,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,0.45811,2.45176,2015,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
310,Benin,Sub-Saharan Africa,153,3.484,NaN,0.39499,0.10419,0.21028,0.39747,0.06681,0.20180,2.10812,2016,3.404,3.564
311,Afghanistan,Southern Asia,154,3.360,NaN,0.38227,0.11037,0.17344,0.16430,0.07112,0.31268,2.14558,2016,3.288,3.432
312,Togo,Sub-Saharan Africa,155,3.303,NaN,0.28123,0.00000,0.24811,0.34678,0.11587,0.17517,2.13540,2016,3.192,3.414
313,Syria,Middle East and Northern Africa,156,3.069,NaN,0.74719,0.14866,0.62994,0.06912,0.17233,0.48397,0.81789,2016,2.936,3.202
314,Burundi,Sub-Saharan Africa,157,2.905,NaN,0.06831,0.23442,0.15747,0.04320,0.09419,0.20290,2.10404,2016,2.732,3.078

we don't have "Standard Error" in df16. So, we have many NaN in concat.

In [16]:
df17["year"] = 2017
all3 = pd.concat([df15, df16, df17], ignore_index=True, sort=True)
all3.columns

Index(['Country', 'Dystopia Residual', 'Dystopia.Residual',
       'Economy (GDP per Capita)', 'Economy..GDP.per.Capita.', 'Family',
       'Freedom', 'Generosity', 'Happiness Rank', 'Happiness Score',
       'Happiness.Rank', 'Happiness.Score', 'Health (Life Expectancy)',
       'Health..Life.Expectancy.', 'Lower Confidence Interval', 'Region',
       'Standard Error', 'Trust (Government Corruption)',
       'Trust..Government.Corruption.', 'Upper Confidence Interval',
       'Whisker.high', 'Whisker.low', 'year'],
      dtype='str')

we have "Happiness.Score" in df2017 instead of "Happiness Score"

In [17]:
df17 = df17.rename(columns={"Happiness.Score": "Happiness Score", "Happiness.Rank": "Happiness Rank"})

In [18]:
#placing part of two datasets side by side:
a=df15[["Country" , "Happiness Score"]]
b=df19[["Country or region" , "Score"]]

side = pd.concat([a,b],axis = 1)
side.head()

       Country  Happiness Score Country or region  Score
0  Switzerland            7.587           Finland  7.769
1      Iceland            7.561           Denmark  7.600
2      Denmark            7.527            Norway  7.554
3       Norway            7.522           Iceland  7.494
4       Canada            7.427       Netherlands  7.488

In [19]:
df19 = df19.rename(columns={"Country or region": "Country"})

h15 = df15[["Country", "Happiness Score"]]
h19 = df19[["Country", "Score"]]

inner = pd.merge(h15, h19, how="inner", on="Country")
print(len(h15), len(h19), len(inner))

inner["change"] = inner["Score"] - inner["Happiness Score"]
inner.sort_values("change", ascending=False).head()

158 156 149

          Country  Happiness Score  Score  change
145         Benin            3.340  4.883   1.543
141   Ivory Coast            3.655  4.944   1.289
148          Togo            2.839  4.085   1.246
98       Honduras            4.788  5.860   1.072
142  Burkina Faso            3.587  4.587   1.000

In [ ]:
left = h15.merge(h19, how="left", on="Country")
left[left["Score"].isna()]

right = h15.merge(h19, how="right", on="Country")
right[right["Happiness Score"].isna()]

#length of left is equal to h15!
print(len(left), len(h15))
print(len(right), len(h19))

158 158
156 156

In [22]:
left

         Country  Happiness Score  Score
0    Switzerland            7.587  7.480
1        Iceland            7.561  7.494
2        Denmark            7.527  7.600
3         Norway            7.522  7.554
4         Canada            7.427  7.278
..           ...              ...    ...
153       Rwanda            3.465  3.334
154        Benin            3.340  4.883
155        Syria            3.006  3.462
156      Burundi            2.905  3.775
157         Togo            2.839  4.085

[158 rows x 3 columns]

In [23]:
right

                      Country  Happiness Score  Score
0                     Finland            7.406  7.769
1                     Denmark            7.527  7.600
2                      Norway            7.522  7.554
3                     Iceland            7.561  7.494
4                 Netherlands            7.378  7.488
..                        ...              ...    ...
151                    Rwanda            3.465  3.334
152                  Tanzania            3.781  3.231
153               Afghanistan            3.575  3.203
154  Central African Republic            3.678  3.083
155               South Sudan              NaN  2.853

[156 rows x 3 columns]

In [24]:
outer = pd.merge(h15, h19, how="outer", on="Country", indicator=True, sort=True)

outer["_merge"].value_counts()

_merge
both          149
left_only       9
right_only      7
Name: count, dtype: int64